version: '3.9'

services:
  caddy-server:
    image: caddy:2-alpine
    restart: unless-stopped
    container_name: caddy-server
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data"
      - "caddy-config:/config"
      - "staticfiles-data:/srv/static"
      - "mediafiles-data:/srv/media"

  app:
    image: app:latest
    container_name: app
    env_file: .env
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - "./app/:/app/"
      - "staticfiles-data:/app/staticfiles"
      - "mediafiles-data:/app/mediafiles"
    depends_on:
      - caddy-server
      - database

  database:
    image: postgres:15-bullseye
    restart: always
    container_name: database
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    env_file: .env
    ports:
      - "5433:5432"

volumes:
  postgres-data:
    external: true
  caddy-data:
    external: true
  caddy-config:
  staticfiles-data:
  mediafiles-data:
